#!/usr/bin/env node
/* Generates client/refdata.js — a browser-loadable bundle of the biomarker
   data layer and the reference-range layer, so the personal dashboard works
   when opened directly from disk (file://).

   Run after tools/standardize.js or after data/reference_ranges.json changes.
   Usage:  node tools/build-client.js [project-root] */

'use strict';
const fs = require('fs');
const path = require('path');

const ROOT = process.argv[2] || '.';
const biomarkers = JSON.parse(fs.readFileSync(path.join(ROOT, 'data/biomarkers.json'), 'utf8'));

let reference = { meta: {}, ranges: {} };
try {
  reference = JSON.parse(fs.readFileSync(path.join(ROOT, 'data/reference_ranges.json'), 'utf8'));
} catch (e) {
  console.warn('note: data/reference_ranges.json not found — dashboard will run with no scoring layer');
}

const banner = '/* GENERATED by tools/build-client.js — do not edit by hand.\n' +
  '   Sources: data/biomarkers.json, data/reference_ranges.json */\n';
const out = banner +
  'window.BIOMARKER_DATA = ' + JSON.stringify(biomarkers) + ';\n' +
  'window.REFERENCE_RANGES = ' + JSON.stringify(reference) + ';\n';

fs.writeFileSync(path.join(ROOT, 'client/refdata.js'), out);
const n = Object.keys(reference.ranges || {}).length;
console.log('Wrote client/refdata.js (' + biomarkers.biomarkers.length +
  ' biomarkers, ' + n + ' reference entries)');
